// <auto-generated />
using System;
using DummyAuthorizationProvider.Data.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DummyAuthorizationProvider.Data.Db.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240519144959_AddVotedFlag")]
    partial class AddVotedFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DummyAuthorizationProvider.Contracts.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Voted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Oib")
                        .IsUnique();

                    b.ToTable("Voters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ca93c30-46f1-42a9-8b6b-2d5d376e0fdd"),
                            Oib = "00000000001",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("3c6ae40e-0b81-4370-aff2-36e240dd4682"),
                            Oib = "00000000002",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("51d51901-ae9d-4dde-b98c-926005760f31"),
                            Oib = "00000000003",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("afa12b37-9f54-46bb-a4cc-76681b7322c8"),
                            Oib = "00000000004",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("8fc12e7d-5438-46c5-b75f-d2824fcbb148"),
                            Oib = "00000000005",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("cf574333-2dbb-4a33-ac7b-631ef3934f37"),
                            Oib = "00000000006",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("126fede2-ff22-4de9-b622-33bffbdea807"),
                            Oib = "00000000007",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("664e814b-5480-42a3-ba3d-300420571723"),
                            Oib = "00000000008",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("a2849b8e-2043-4a04-a847-7e16a89d0e66"),
                            Oib = "00000000009",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("209d91f2-3112-4a08-a544-3d3608efafd8"),
                            Oib = "00000000010",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("25b58a1a-0493-4fc9-a794-2d85e068b335"),
                            Oib = "00000000011",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("de7776bf-7a59-4af4-838b-702c2355fe8c"),
                            Oib = "00000000012",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("de3d5472-68c1-43ea-96f0-e85fce7c127b"),
                            Oib = "00000000013",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("91684903-df50-4ef6-95ca-648f035f0099"),
                            Oib = "00000000014",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("5fade656-748c-42ed-a73e-01a81c2f3a6e"),
                            Oib = "00000000015",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("9b454077-33c9-402e-b543-5a91cddd687a"),
                            Oib = "00000000016",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("e33b6f85-1608-421d-bf90-b1dff6383cd5"),
                            Oib = "00000000017",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("fa581021-62c3-49a6-8998-edc0bdbe85d1"),
                            Oib = "00000000018",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("e87b5d90-355e-489c-a594-48f4fdb9d7a0"),
                            Oib = "00000000019",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("3a1409b5-5ee9-4c17-b708-11fb7af152c1"),
                            Oib = "00000000020",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("82099ceb-c68d-4556-b46f-f9210b2f29f8"),
                            Oib = "00000000021",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("1e54664d-e49d-4bb9-b4b8-4f7bb957ac68"),
                            Oib = "00000000022",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("f1af54cf-6058-4724-ad52-55f61ed70976"),
                            Oib = "00000000023",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("566f1c36-56ea-4b7f-a63e-b9576f80268a"),
                            Oib = "00000000024",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("83e6f05d-e2b6-49b9-afc8-7372575d69df"),
                            Oib = "00000000025",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("72e21ed6-bb10-466c-a0e6-f120a44d4872"),
                            Oib = "00000000026",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("13f086ae-cd5a-4b3a-9df8-26e4cf2f25f7"),
                            Oib = "00000000027",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("828781bd-699c-4334-9a11-aa35a2d18b13"),
                            Oib = "00000000028",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("866962d5-da8b-4295-8045-73a9ce0cdcc2"),
                            Oib = "00000000029",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("0804bfab-fd46-44da-bfb7-2df5aa5b8305"),
                            Oib = "00000000030",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("a1e71cad-538f-49d7-8a59-4fb025fe5fba"),
                            Oib = "00000000031",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("dbfb9fe8-262c-43c6-9c44-4aeea0f29a4a"),
                            Oib = "00000000032",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("dcdb26b2-48e5-44f1-8fd0-25735fd11430"),
                            Oib = "00000000033",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("f49d87a7-84ee-44af-ba9e-076e594d3beb"),
                            Oib = "00000000034",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("e64db21b-7723-479d-89d0-2652f65edadf"),
                            Oib = "00000000035",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("7e3f76f5-a66c-4efb-ab14-4c08c18e90ae"),
                            Oib = "00000000036",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("e3f54371-2017-46ae-8beb-5c3e28acaf23"),
                            Oib = "00000000037",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("3ffaa24e-f01b-4d4b-9d8f-2b5b2e8f5c9d"),
                            Oib = "00000000038",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("874e27ad-93db-4b1e-b05a-6fd086218dea"),
                            Oib = "00000000039",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("404608aa-a547-44a1-933b-c0748616e9c0"),
                            Oib = "00000000040",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("28e20622-0e86-48a5-ad13-9499ab1175ae"),
                            Oib = "00000000041",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("750e0e8d-9720-441a-860f-d77c89b2addb"),
                            Oib = "00000000042",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("080c575c-d419-44e6-be53-1b9c9f2a9c44"),
                            Oib = "00000000043",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("fdc4e8aa-23b4-4a8d-84b1-26628f2719c7"),
                            Oib = "00000000044",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("c7d21216-b136-4033-a0a9-901a51474ad5"),
                            Oib = "00000000045",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("6248f48d-2ced-43c0-81f7-170476eea46c"),
                            Oib = "00000000046",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("e710e161-9919-4fa0-b61f-5b34e97ce3e6"),
                            Oib = "00000000047",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("dee25a1d-f915-4415-971e-40a51d9df00b"),
                            Oib = "00000000048",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("eaf8617d-8ad7-4506-a4de-95089d7d07eb"),
                            Oib = "00000000049",
                            Voted = false
                        },
                        new
                        {
                            Id = new Guid("17db2473-f729-496a-a88a-c113f9caba3f"),
                            Oib = "00000000050",
                            Voted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
