// <auto-generated />
using System;
using DummyAuthorizationProvider.Data.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DummyAuthorizationProvider.Data.Db.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240519185406_AddVoterStatus")]
    partial class AddVoterStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DummyAuthorizationProvider.Contracts.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Oib")
                        .IsUnique();

                    b.ToTable("Voters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f9c7f10-5447-476b-bd5b-3bc25427e773"),
                            Oib = "00000000001",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6fd8eb2d-43a3-4c92-ab4a-8fe7eb26a4a0"),
                            Oib = "00000000002",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("509b1511-ae41-4673-8f46-0f5b3a42f5fe"),
                            Oib = "00000000003",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("52b0e385-cf90-49bf-9731-5be51250f1aa"),
                            Oib = "00000000004",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2c465bd6-9b21-48db-87a4-d8c5a07477d7"),
                            Oib = "00000000005",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("809a5460-30ad-4d41-b000-bb030379e737"),
                            Oib = "00000000006",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("161c6240-4795-4898-a963-e215f0b0c787"),
                            Oib = "00000000007",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4f3f8d48-b719-47ca-a987-1ff6848202d5"),
                            Oib = "00000000008",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a9f9c807-678b-42bf-b617-a421a1cb1f7b"),
                            Oib = "00000000009",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("278fed60-c729-4694-a8da-d95a05e9efc3"),
                            Oib = "00000000010",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("76fb7dfb-8e62-4bbd-89af-a93733f8e930"),
                            Oib = "00000000011",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e26b78c3-a123-48b8-9b7e-04bbdb83d06e"),
                            Oib = "00000000012",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c2bd42a7-fafb-4629-8613-0a672959c541"),
                            Oib = "00000000013",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3358d670-5582-4e26-bc75-d815e661e519"),
                            Oib = "00000000014",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9c10babe-6026-42c0-888b-4d587b46b70c"),
                            Oib = "00000000015",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("290cfe11-ce29-4d67-bec1-fc097154af83"),
                            Oib = "00000000016",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("45f38d89-919d-4447-bea8-1aaaa833dfbf"),
                            Oib = "00000000017",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("71e349c5-444d-4c9c-b35c-1e4cdd0eef0b"),
                            Oib = "00000000018",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("666a216b-2494-4120-92bd-08c5327405d4"),
                            Oib = "00000000019",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("87704913-201f-4431-a69a-5ad75faba5a0"),
                            Oib = "00000000020",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a72b3636-fbdc-436b-b849-94b44363d660"),
                            Oib = "00000000021",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2d66593d-5a59-461a-a776-5eb3c55a0190"),
                            Oib = "00000000022",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("301fbfa4-2080-4ce0-b6be-3982e25f9af3"),
                            Oib = "00000000023",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1908a9ec-ddc9-4215-b44c-14a89d7a48ed"),
                            Oib = "00000000024",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c5c44ee4-3e88-4659-ac94-84d739914b2c"),
                            Oib = "00000000025",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ac04e0f5-368d-44aa-a7e6-56a5a3e0d171"),
                            Oib = "00000000026",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbecfccd-4a35-4472-8a8b-0007d5bc9e31"),
                            Oib = "00000000027",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6b267ed4-a909-4e48-a796-d45f23c14374"),
                            Oib = "00000000028",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("14714a54-8f2f-4915-aa9a-50db88806622"),
                            Oib = "00000000029",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9914bd96-43c3-4032-8a64-7c7bb0cd514b"),
                            Oib = "00000000030",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c6d98fe9-bb23-41b7-8e98-9e5a511ef6cb"),
                            Oib = "00000000031",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("85bb3c4c-9bb0-401f-9a43-d9e44e40d85b"),
                            Oib = "00000000032",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("36a36d36-8f92-4f99-9ca7-7ab06252505f"),
                            Oib = "00000000033",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3b24198a-d365-4a7b-b911-7d4429e8298f"),
                            Oib = "00000000034",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("211efad3-e432-4394-9009-49093b2b3e29"),
                            Oib = "00000000035",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6740f328-8b1c-43ce-bc97-57e7681c4550"),
                            Oib = "00000000036",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b972ba17-4c3a-4c47-bab1-f6e64f4322ef"),
                            Oib = "00000000037",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9aebe18e-8d63-4639-b01d-9f0d5d02f374"),
                            Oib = "00000000038",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3135d51c-1133-4b4e-bf30-563d34154edf"),
                            Oib = "00000000039",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c010f02b-c391-4f69-8f5d-e29e5c658821"),
                            Oib = "00000000040",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c281a2dc-50db-4d39-b3b1-9b8572c3d22c"),
                            Oib = "00000000041",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("51ecedcd-5706-4309-b14e-04e505b88ffb"),
                            Oib = "00000000042",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ad7d8c14-8169-418b-9529-4ee7ca482d82"),
                            Oib = "00000000043",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a1fc710e-378b-495d-81d7-25b1f0e68952"),
                            Oib = "00000000044",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("52a58a45-c788-4b3f-8ad5-a71bd1557dd6"),
                            Oib = "00000000045",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3b6d4c9a-cd5a-4fd5-bf37-f8a00e5d0d4f"),
                            Oib = "00000000046",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dc728698-cf9b-40d7-a2c1-ce2d8d85031e"),
                            Oib = "00000000047",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9d84b3e1-d8b4-4141-98a9-ae4901eef276"),
                            Oib = "00000000048",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b8f97deb-b47d-4aa1-afbd-fca77891b241"),
                            Oib = "00000000049",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("79ff6bcc-2d28-44e7-b81c-6a88867c9e89"),
                            Oib = "00000000050",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
